//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class totexp
    {
        public int id { get; set; }
        public Nullable<int> totexp1 { get; set; }
    }
}
